### ISSUE TITLE
Word count for each content entry

### ISSUE THREAD

**Issue by rosathoneick** [micado-eu/ngo_application#16]
We need a word count for each entry (information portal, glossary, guided processes etc) in order to be able to have an overview on the amount of text that is going to be translated. Otherwise we cannot oversee the effort and thus monitor the cost of translation

**Comment by ivchicano** [comment]
Word counter has been added to the text editor.
![chrome_YOZ7Uh1x4c](https://user-images.githubusercontent.com/46921761/102476803-cf5b4980-405b-11eb-85b2-473511a13b63.png)
