### ISSUE TITLE
Possibility of sharing documents with migrant users

### ISSUE THREAD

**Issue by Colpolsoc** [micado-eu/ngo_application#19]
Documents section in the CSO app: Possibility of uploading and sharing documents (such as course completion certificates) with migrant users. Especially useful for issuing duplicates. [LESC Madrid]

**Comment by GiuseppeCSI** [comment]
There is already a similar function. When a migrant user completes a task in one of the integration plans and asks for confirmation, the cso user can mark the task as complete and also attach a document (which could be the course completion certificate for example). The document will appear in the migrant's document wallet where he can download it as any times as he needs.

**Comment by Colpolsoc** [comment]
Thanks for your answer! Will this feature be available only for integration plan tasks or will it be included also in the guided processes?

**Comment by gioppoluca** [comment]
No, guided processes are managed by the PA, and ONLY PA has the right to describe the process.  So NGO has no document to add in that flow.
