### ISSUE TITLE
Provide annotation possibility for NGO users

### ISSUE THREAD

**Issue by balcse** [micado-eu/ngo_application#21]
Rethink and redesign the comment function:
NGO users should be able to provide concrete annotations in the steps themselves (not only basic comments), as this is an USP for the app

**Comment by gioppoluca** [comment]
Will not implement.
Having comments in the steps will clutter the migrant view.
You have to consider that many NGO could add their own comments and imagine each one adding a comment in each step.
The generated mess would be big.
In the description of the comment you can describe all you want regarding the steps
